###
GET https://node-mongodb-ul6k.onrender.com/

###
POST https://node-mongodb-ul6k.onrender.com/
content-type: application/json

{
    "name":"newmovie"
}

###
PUT https://node-mongodb-ul6k.onrender.com/newmovie
Content-Type: application/json

{
    "name":"Beautiful Days"
}

###
DELETE https://node-mongodb-ul6k.onrender.com/newmovie