###
GET https://node-mongodb-ul6k.onrender.com/

###
POST https://node-mongodb-ul6k.onrender.com/
content-type: application/json

{
    "name":"newmovie"
}

###
PUT https://node-mongodb-ul6k.onrender.com/newMovie
Content-Type: application/json

{
    "name":"Alexander The Great"
}

###
DELETE https://node-mongodb-ul6k.onrender.com/newMovie